print("Hola Mundo")
print(type("Hola Mundo")) 
print([1, 10, 100])
print(type([1, 10, 100]))
print(-25)          
print(type(-25))
print(1.167)
print(type(1.167))       
print(["Hola", "Mundo"])
print(type(["Hola", "Mundo"]))  
print(' ')
print(type(' '))
print(True)
print(type(True)) 
print({'Uno':"uno", 'Dos':"dos"}) 
print(type({'Uno':"uno", 'Dos':"dos"}))  
